name: "Netatmo TrueTemp API"
slug: "netatmo_truetemp"
description: "HTTP wrapper for py-netatmo-truetemp-cli"
version: "0.1.0"

arch:
  - aarch64
  - amd64

startup: services
boot: auto
init: false

ingress: false
panel: false

ports:
  8099/tcp: 8099

ports_description:
  8099/tcp: "HTTP API"

options:
  username: ""
  password: ""
  home_id: ""

schema:
  username: str
  password: password
  home_id: str?
